BootstrapTemplate/BootstrapTemplate/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace BootstrapTemplate.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

BootstrapTemplate/BootstrapTemplate/ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BootstrapTemplate.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

BootstrapTemplate/BootstrapTemplate/Controllers/AboutController.cs
using System.Web.Mvc;

namespace BootstrapTemplate.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

BootstrapTemplate/BootstrapTemplate/Controllers/BlogController.cs
using System.Web.Mvc;


namespace BootstrapTemplate.Controllers
{
    
    
    public class BlogController : Controller
    {
    }
}

BootstrapTemplate/BootstrapTemplate/Controllers/ContactController.cs
using System.Web.Mvc;

namespace BootstrapTemplate.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

BootstrapTemplate/BootstrapTemplate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootstrapTemplate.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BootstrapTemplate/BootstrapTemplate/Controllers/OtherController.cs
using System.Web.Mvc;


namespace BootstrapTemplate.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
    }
}

BootstrapTemplate/BootstrapTemplate/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace BootstrapTemplate.Controllers
{
    
    
    public class PortfolioController : Controller
    {
    }
}

BootstrapTemplate/BootstrapTemplate/Controllers/ServicesController.cs
using System.Web.Mvc;

namespace BootstrapTemplate.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

BootstrapTemplate/BootstrapTemplate/Views/About/Index.cshtml
@{
    ViewBag.Title = "About";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                About
                <small>It's Nice to Meet You!</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li class="active">About</li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <img src="http://placehold.it/750x450" class="img-responsive">
    </div>
    <div class="col-md-6">
        <h2>Welcome to 'Modern Business'</h2>
        <p>This is a great place to introduce your company or project and describe what you do. This about page features general company information, employee bios, and other helpful elements.</p>
        <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
    </div>
</div>
<!-- Team Member Profiles -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Team</h2>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
</div>
<!-- Our Customers -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Customers</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
</div>
</div>

BootstrapTemplate/BootstrapTemplate/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact <small>We'd Love to Hear From You!</small></h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Contact</li>
            </ol>
        </div>
        <div class="col-lg-12">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" scrolling="no" height="400px" frameborder="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed" marginwidth="0" marginheight="0"></iframe>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-sm-8">
            <h3>Let's Get In Touch!</h3>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <form action="contact-form-submission.php" method="POST" role="form">
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label for="input1">Name</label>
                        <input type="text" id="input1" class="form-control" name="contact_name">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input2">Email Address</label>
                        <input type="email" id="input2" class="form-control" name="contact_email">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input3">Phone Number</label>
                        <input type="phone" id="input3" class="form-control" name="contact_phone">
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-lg-12">
                        <label for="input4">Message</label>
                        <textarea id="input4" rows="6" class="form-control" name="contact_message"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="hidden" value="contact" name="save">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-4">
            <h3>Modern Business</h3>
            <h4>A Start Bootstrap Template</h4>
            <p>
                5555 44th Street N.<br>
                Bootstrapville, CA 32323<br>
            </p>
            <p><i class="fa fa-phone"></i> <abbr title="Phone">P</abbr>: (555) 984-3600</p>
            <p><i class="fa fa-envelope-o"></i> <abbr title="Email">E</abbr>: <a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a></p>
            <p><i class="fa fa-clock-o"></i> <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
            <ul class="list-unstyled list-inline list-social-icons">
                <li class="tooltip-social facebook-link"><a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-page"><i class="fa fa-facebook-square fa-2x"></i></a></li>
                <li class="tooltip-social linkedin-link"><a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-company-page"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
                <li class="tooltip-social twitter-link"><a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a></li>
                <li class="tooltip-social google-plus-link"><a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-page"><i class="fa fa-google-plus-square fa-2x"></i></a></li>
            </ul>
        </div>
    </div><!-- /.row -->
</div>

BootstrapTemplate/BootstrapTemplate/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
            <div class="carousel-caption">
                <h1>Modern Business - A Bootstrap 3 Template</h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
            <div class="carousel-caption">
                <h1>Ready to Style &amp; Add Content</h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
            <div class="carousel-caption">
                <h1>
                    Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
                </h1>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>

<div class="section">

    <div class="container">

        <div class="row">
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-check-circle"></i> Bootstrap 3 Built</h3>
                <p>The 'Modern Business' website template by <a href="http://startbootstrap.com">Start Bootstrap</a> is built with <a href="http://getbootstrap.com">Bootstrap 3</a>. Make sure you're up to date with latest Bootstrap documentation!</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-pencil"></i> Ready to Style &amp; Edit</h3>
                <p>You're ready to go with this pre-built page structure, now all you need to do is add your own custom stylings! You can see some free themes over at <a href="http://bootswatch.com">Bootswatch</a>, or come up with your own using <a href="http://getbootstrap.com/customize/">the Bootstrap customizer</a>!</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-folder-open"></i> Many Page Options</h3>
                <p>This template features many common pages that you might see on a business website. Pages include: about, contact, portfolio variations, blog, pricing, FAQ, 404, services, and general multi-purpose pages.</p>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

</div>
<!-- /.section -->

<div class="section-colored text-center">

    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <h2>Modern Business: A Clean &amp; Simple Full Website Template by Start Bootstrap</h2>
                <p>A complete website design featuring various single page templates from Start Bootstraps library of free HTML starter templates.</p>
                <hr>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

</div>
<!-- /.section-colored -->

<div class="section">

    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Display Some Work on the Home Page Portfolio</h2>
                <hr>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                </a>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

</div>
<!-- /.section -->

<div class="section-colored">

    <div class="container">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <h2>Modern Business Features Include:</h2>
                <ul>
                    <li>Bootstrap 3 Framework</li>
                    <li>Mobile Responsive Design</li>
                    <li>Predefined File Paths</li>
                    <li>Working PHP Contact Page</li>
                    <li>Minimal Custom CSS Styles</li>
                    <li>Unstyled: Add Your Own Style and Content!</li>
                    <li>Font-Awesome fonts come pre-installed!</li>
                    <li>100% <strong>Free</strong> to Use</li>
                    <li>Open Source: Use for any project, private or commercial!</li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <img class="img-responsive" src="http://placehold.it/700x450/ffffff/cccccc">
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

</div>
<!-- /.section-colored -->

<div class="section">

    <div class="container">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <img class="img-responsive" src="http://placehold.it/700x450">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <h2>Modern Business Features Include:</h2>
                <ul>
                    <li>Bootstrap 3 Framework</li>
                    <li>Mobile Responsive Design</li>
                    <li>Predefined File Paths</li>
                    <li>Working PHP Contact Page</li>
                    <li>Minimal Custom CSS Styles</li>
                    <li>Unstyled: Add Your Own Style and Content!</li>
                    <li>Font-Awesome fonts come pre-installed!</li>
                    <li>100% <strong>Free</strong> to Use</li>
                    <li>Open Source: Use for any project, private or commercial!</li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

</div>
<!-- /.section -->

<div class="container">

    <div class="row well">
        <div class="col-lg-8 col-md-8">
            <h4>'Modern Business' is a ready-to-use, Bootstrap 3 updated, multi-purpose HTML theme!</h4>
            <p>For more templates and more page options that you can integrate into this website template, visit Start Bootstrap!</p>
        </div>
        <div class="col-lg-4 col-md-4">
            <a class="btn btn-lg btn-primary pull-right" href="http://startbootstrap.com">See More Templates!</a>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

BootstrapTemplate/BootstrapTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("My Bootstrap Site", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                       @Html.ActionLink("About", "Index", "About")
                    </li>
                    <li id="services">
                        @Html.ActionLink("Services", "Index", "Services")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Contact", "Index", "Contact")
                    </li>
                    
                    
                    <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            
                            
                            
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
<div>

            <script>
                $(document).ready(function () {
                    (function () {
                        var flickerAPI = "http://localhost:51393/RESTService.svc/json/10";
                        alert('solicitar datos');
                        $.getJSON(flickerAPI, {
                            format: "json"
                        })
                          .done(function (data) {
                              $.each(data.items, function (i, item) {
                                  document.write(item.lastname);
                              });
                              alert(data);
                          });
                    })();
                });

            </script>
</div>
</body>
</html>